const colors = {
  light: {
    text: "#F8FAFC",
    tint: "#60A5FA",
    background: "#0F172A",
    foreground: "#F8FAFC",
    card: "#1E293B",
    cardForeground: "#F8FAFC",
    primary: "#60A5FA",
    primaryForeground: "#0F172A",
    secondary: "#1E293B",
    secondaryForeground: "#F8FAFC",
    muted: "#1E293B",
    mutedForeground: "#94A3B8",
    accent: "#FB923C",
    accentForeground: "#0F172A",
    destructive: "#F87171",
    destructiveForeground: "#FFFFFF",
    border: "#2D4A6A",
    input: "#2D4A6A",
  },
  dark: {
    text: "#F8FAFC",
    tint: "#60A5FA",
    background: "#0F172A",
    foreground: "#F8FAFC",
    card: "#1E293B",
    cardForeground: "#F8FAFC",
    primary: "#60A5FA",
    primaryForeground: "#0F172A",
    secondary: "#1E293B",
    secondaryForeground: "#F8FAFC",
    muted: "#1E293B",
    mutedForeground: "#94A3B8",
    accent: "#FB923C",
    accentForeground: "#0F172A",
    destructive: "#F87171",
    destructiveForeground: "#FFFFFF",
    border: "#2D4A6A",
    input: "#2D4A6A",
  },
  radius: 12,
};

export default colors;
